# Generated by Django 4.1.5 on 2023-01-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_motherboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='socket',
            field=models.CharField(choices=[('LGA12', 'LGA 1200'), ('LGA17', 'LGA 1700'), ('AM4', 'AM4')], default='LGA12', max_length=20),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='socket',
            field=models.CharField(choices=[('LGA12', 'LGA 1200'), ('LGA17', 'LGA 1700'), ('AM4', 'AM4')], default='LGA12', max_length=20),
        ),
    ]
