# Generated by Django 4.1.5 on 2023-01-26 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_cpu_socket_motherboard_socket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('official', 'Официальная'), ('custom', 'Пользовательская')], default='custom', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('CPU', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='configurator.cpu')),
                ('Case', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='configurator.case')),
                ('GPU', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='configurator.gpu')),
                ('HDD', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='configurator.hdd')),
                ('Motherboard', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='configurator.motherboard')),
                ('PowerSupply', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='configurator.powersupply')),
                ('RAM', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='configurator.ram')),
                ('SSD', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='configurator.ssd')),
            ],
        ),
    ]
