# Generated by Django 4.1.5 on 2023-01-26 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0004_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='CPU',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='configurator.cpu'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='Case',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='configurator.case'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='GPU',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='configurator.gpu'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='HDD',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='configurator.hdd'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='Motherboard',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='configurator.motherboard'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='PowerSupply',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='configurator.powersupply'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='RAM',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='configurator.ram'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='SSD',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='configurator.ssd'),
        ),
    ]
