# Generated by Django 4.1.5 on 2023-01-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0005_alter_configuration_cpu_alter_configuration_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='purpose',
            field=models.CharField(choices=[('gaming', 'Игровая'), ('office', 'Для офиса'), ('home', 'Домашняя')], default='home', max_length=120),
        ),
    ]
