# Generated by Django 4.1.5 on 2023-01-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0006_configuration_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
